# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 031f6d99d510e450cc3b3b69104c30f26251f80047805e0af53d560b2535417206ee58a04e4f0162e849a92c62a58e74c61425cc2b0ab27b97b74ca974334543

test:
  secret_key_base: 8a807f8df82888a3a1775c6ace86599b24ea365d45e5d8658da591891e783c418cb005531765a7fe8200f4266b9ec3b07ce5e302b4bc7fa2a0490248a13c1868

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
